tortuga/resourceAdapter/aws/awsHelpers.py
Addresses issue #1 where default region isn't set to expected value.
=> Fix default region (us-east-1) detection

src/tortuga/scripts/setup_aws.py
=> Setup aws updates

src/tortuga/resourceAdapter/aws/aws.py
=> Fix handling of dns_nameservers setting

src/tortuga/resourceAdapter/aws/aws.py
=> Do not set empty string as public dns name

kit.json, src/tortuga/resourceAdapter/aws/aws.py
Using `add-nodes --ip-addr` when adding AWS instances
=> Allow setting IP address of instances

src/tortuga/resourceAdapter/aws/aws.py
Add support for IAM instance profile, tags, and block devices
to spot fleet requests
=> Fleet attribute enhancements

src/tortuga/resourceAdapter/aws/aws.py
=> Raise exception if invalid AWS region is specified

src/tortuga/resourceAdapter/aws/aws.py
Resolves https://github.com/UnivaCorporation/tortuga-kit-awsadapter/issues/149
=> Check for existence of aws-instances.csv

src/tortuga/resourceAdapter/aws/aws.py
Closes https://github.com/UnivaCorporation/tortuga-kit-awsadapter/issues/151
=> Support non-spot node insertion

tests/conftest.py, tests/test_aws.py
Note: these fixes will not succeed until the other outstanding PRs are accepted/closed.
=> Update unit tests for latest code

src/tortuga/resourceAdapter/aws/aws.py, src/tortuga/scripts/setup_aws.py
=> Fix misnamed resource adapter configuration settings

src/tortuga/resourceAdapter/aws/aws.py
=> Set vcpus correctly for spot instances

src/tortuga/resourceAdapter/aws/aws.py, src/tortuga/scripts/awsspotd.py
=> Support dns suffix override on spot instances

kit.json, tortuga_kits/awsadapter_7_0_3/puppet_modules/univa-tortuga_kit_awsadapter/.gitignore, tortuga_kits/awsadapter_7_0_3/puppet_modules/univa-tortuga_kit_awsadapter/lib/puppet/parser/functions/kit_info.rb, tortuga_kits/awsadapter_7_0_3/puppet_modules/univa-tortuga_kit_awsadapter/manifests/params.pp
Get kit version information from the embedded kit.json file.
=> Read kit version info from embedded kit.json

src/tortuga/resourceAdapter/aws/aws.py, src/tortuga/resourceAdapter/aws/helpers.py, src/tortuga/resourceAdapter/aws/launchRequest.py, tests/test_aws.py
This is a port of #187 (on the 7.0.3 branch) to master, please see that PR for more details.  The code changes are effectively the same, I've ported the same unit tests over, and run the same integration tests in-place on AWS.
=> Launch instance with tags

tortuga_kits/awsadapter/files/bootstrap.debian.tmpl, tortuga_kits/awsadapter/files/bootstrap.tmpl
=> Fix bootstrap for Amazon Linux and Ubuntu

src/tortuga/resourceAdapter/aws/aws.py
The low-level `boto3` client to the EC2 API doesn't seem to automatically encode the user data as base64 for you (as the corresponding service resource does), so this adds the ability to do optional user data encoding when compiling the common launch args.
Necessary to make scale set creation work when specifying a hardware or software profile.
=> Add optional user data encoding with boto3

tortuga_kits/awsadapter/files/bootstrap-aws-centos7.py, tortuga_kits/awsadapter/files/bootstrap-aws-centos8.py, tortuga_kits/awsadapter/files/bootstrap-aws-ubuntu18.py
Fix a variety of minor issues with the new bootstrap scripts
=> Bootstrap script fixes

tortuga_kits/awsadapter/files/bootstrap-aws-centos7.py, tortuga_kits/awsadapter/files/bootstrap-aws-centos8.py, tortuga_kits/awsadapter/files/bootstrap-aws-ubuntu18.py
* Fix DNS setup without `override_dns_domain` (for Azure)
* Reduce size of bootstrap scripts (for AWS)
Changes identical for all three scripts and in all of the adapter kits. Tested in all cloud providers.
=> Bootstrap fixes

src/tortuga/resourceAdapter/aws/aws.py
This change makes sure we always pass 'str' price types as
that is what the API expects (boto2 seems to deal with floats
against its docs though).  Also make sure to only enable spot
on launch_templates if requested through adapter overrides or
on profiles with `enable_spot` specifically set.
=> Make sure we pass proper spot_price type

src/tortuga/resourceAdapter/aws/aws.py
This PR implements a check on whether an AMI exists before attempting to get its block device mappings, for both `boto` and `boto3` connections.  The `boto` documentation states that `get_image` returns `None` if the AMI is not found, but I have found that it just raises an exception in that case. However, I still implemented a check on whether the AMI is `None` in that case, just to be safe.
When the AMI does not exist, the following error messages should now show up the celery logs.
`boto3`:
```
[2020-09-18 14:38:52,527: ERROR/ForkPoolWorker-3] Invalid AMI: An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-14c5486b]' does not exist
```
`boto` (only used for spot requests at present):
```
[2020-09-18 14:38:07,633: …
```
=> Add AMI validity check for block device mappings

src/tortuga/resourceAdapter/aws/aws.py
This change provides the following behaviors for one off and
scale set spot instances:
When Spot is not provided as an override in the addNodes request
If spot is enabled in the resource adapter and no price is set ->
Spot Request is made to AWS with default (ondemand) price.
If spot is enabled and a price is set in the resource adapter ->
Spot Request is made to AWS with provided price
When spot_instance_request is provided as an override but no price
is set:
If spot is enabled and a price is set in the resource adapter ->
Spot request is made to AWS with resource adapter price
If spot is not enabled or a price is not set in the adapter ->
Spot request is made to AWS with default (ondemand price)
When spot_instance_request is provided as an override and a price
is set:
Spot request is …
=> Handle default price behavior for spot instances
