src/tortuga/resourceAdapter/aws/aws.py
src/tortuga/scripts/list_spot_instance_nodes.py
src/tortuga/scripts/setup_aws.py
tests/conftest.py
tortuga_kits/awsadapter_6_3_1/kit.py

The Resource adapter name needs to be AWS and the default
profile needs to be Default so that it looks nice in
web uis.

Switch to 'AWS' and Default strings

---

.travis.yml
src/tortuga/scripts/setup_aws.py

Instead of looking for an amazon linux AMI use the AMI we already
have identified as the one we wish to use with the generated
cloud connector profile.

Use the detected AMI for instance type validation

---

src/tortuga/resourceAdapter/aws/aws.py

Prior to this commit the resource adapter configuration was
not being set in the instance mapping stored in the db.

Properly set instance mapping on spot requests

---

tortuga_kits/awsadapter_7_0_3/puppet_modules/univa-tortuga_kit_awsadapter/.gitignore
tortuga_kits/awsadapter_7_0_3/puppet_modules/univa-tortuga_kit_awsadapter/manifests/params.pp

Some issues addressed:
* $name variable cannot be overridden in puppet
* extra '}' in params.pp
* kit.json can't be in .gitignore as puppet will then refuse to package it

Fix simple errors

---

tortuga_kits/awsadapter_7_0_3/files/aws-bootstrap-offline.tmpl
tortuga_kits/awsadapter_7_0_3/files/bootstrap.debian.tmpl
tortuga_kits/awsadapter_7_0_3/files/bootstrap.python3.tmpl
tortuga_kits/awsadapter_7_0_3/files/bootstrap.tmpl
tortuga_kits/awsadapter_7_0_3/files/bootstrap.tmpl.reverse_dns

1. By touching log file first, works around PUP-7331 that is
causing puppet agent to be run twice on every bootstrap script.
(The first run is a very short failure).
2. By using --no-daemonize, allows subprocess.wait to wait
on the correct child process. Without this the code advances
without blocking on puppet run.

Fix 2 issues with how bootstrap calls puppet agent

---

src/tortuga/resourceAdapter/aws/aws.py
src/tortuga/resourceAdapter/aws/helpers.py
src/tortuga/resourceAdapter/aws/launchRequest.py
tests/test_aws.py

This PR adds the ability to tag EC2 instances and their associated volumes at creation time.  It requires converting the calls to the EC2 API to use `boto3`, as well as adding some functionality to build up the metadata for those calls, since the format differs fairly significantly from the same calls using `boto`.  This PR builds on the information in #184.
I also looked into whether this could also be applied to spot instances, although it sounds like that is not a requirement at present, based on discussions with @tpdownes.  However, it does not appear to be possible to "tag at creation" for spot instance requests or spot instances themselves (see AWS docs [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-ec2-resources-table) and …

[WIP] Tag EC2 instances at creation

---

requirements.txt

The latest release of `azure-cli` requires `colorama~=0.4.1` which means accept versions `0.4.x`. The version of the `awscli` presently in use by the kit requires `colorama>=0.2.5,<=0.3.9`.
This also resolves a problem where PyYAML 5.1.2 is installed but the older version of `awscli` needs a much older version of `pyyaml`. The new `awscli` doesn't need `pyyaml` at all.
I think we should consider removing `colorama` from this file as it is an indirect dependency. I realize there are benefits to `pip freeze` for re-creating an exact known working virtual environment but that's a separate question from actually stating them as requirements for installation. I think we should consider two separate files for these purposes.

Resolve several pip incompatibilities

---

tests/test_aws.py
tests/test_aws_config.py
tests/test_user_data.py

Fix several unit tests that were broken in master:
* `tests/test_aws.py::test_start_update_node` needed an `instancetype` added to the `configDict`
* Several tests in `tests/test_aws_config.py` were using the old syntax for getting the resource adapter configuration, `getResourceAdapterConfig`, which has been updated to `get_config`.

Fix unit tests

---

src/tortuga/resourceAdapter/aws/aws.py

Override `get_initial_tags` method that is inherited from the base `ResourceAdapter` class  to account for the ability of the user to override the automatically-detected installer IP address in this adapter kit.

Use user-defined installer IP setting for tags

---

doc/tortuga-kit-awsadapter.md

The docs currently indicate the old (7.0.3) way of adding tags with spaces between tags and quotes surrounding keys or values with spaces in them, e.g.
```
adapter-mgmt update -r AWS -p Default --setting tags="Name=\"my node name\" other=tag-value"
```
This PR updates the docs with the new syntax, e.g.
```
adapter-mgmt update -r AWS -p Default --setting tags="Name=my node name,other=tag-value"
```

Update documentation on tag formatting

---

src/tortuga/resourceAdapter/aws/aws.py
tests/test_scale_set.py

This PR adds tags to an AWS auto-scaling group at creation time and instructs it to propagate the tags to any instances launched within the group.  It also prevents post-launch tagging for instances in a scale set, as would normally be triggered by the user data script on the instance.
I have tested this live in AWS, using scale sets made up of standard lifecycle instances and spot instances.

Scale set tagging

---

kit.json
src/tortuga/resourceAdapter/aws/aws.py

Add a helper function for trimming `managed:` from tag keys/names before the tags are added to a cloud instance.  The prefix is maintained in the node-tag record in the Tortuga database as a way of internally tracking managed tags.
The helper function was implemented in three places:
* Tag compilation before launching EC2 instances with tags attached
* Tag compilation before creating auto-scaling groups with tags attached
* `_tag_instance` method which is used to tag instances and EBS volumes post-launch
I've tested this in AWS by creating a cloud server using `navopsctl create task task.yaml` with the following content:
```
metadata:
apiVersion: v1
type: Task
spec:
childTaskIds: null
init:
clusterProfileId: 985459ca-3b0b-42fb-88a0-d8b588cc624b
count: 1
tags:
- name: mytag
value: runnow …
```

Implement helper for fixing managed tags

---

src/tortuga/resourceAdapter/aws/aws.py

Store resource adapter configuration in insert node request so that the node can ping the Tortuga API and tell it which resource adapter profile it is using, instead of falling back to the default profile.

Fix spot instance tagging

---

src/tortuga/resourceAdapter/aws/settings.py
tortuga_kits/awsadapter/puppet_modules/univa-tortuga_kit_awsadapter/manifests/management.pp
tortuga_kits/awsadapter/puppet_modules/univa-tortuga_kit_awsadapter/metadata.json

Changes to use boto3 for getting fixed region lists and using
auto detection for new regions boto2 doesn't know about.

Support new AWS regions

---

src/tortuga/resourceAdapter/aws/aws.py

We were checking the `insertnode_request` for a parameter called `apply_tags_post_launch` but it was inserted as `add_tags_post_launch`.  This resulted in attempting to apply tags after an instance was created in a scaleset, even though they were applied at creation.
This fix makes the two uses of this parameter consistent so we prevent attempts at post-facto tagging of instances in scalesets.

fix: post-launch tagging parameter for scalesets

---

src/tortuga/resourceAdapter/aws/aws.py

This commit adds tags included in the `addNodesRequest` to the `insertnode_request` saved in the userdata bootstrap script. When the spot instance boots up and pings the tortuga API, this allows it to tell tortuga about additional tags which should be applied to it that aren't part of the adapter configuration profile.
Getting the tags out of the request data and applying them to the instance is already part of the available functionality in tortuga (see [here](https://github.com/UnivaCorporation/tortuga/blob/master/src/installer/src/tortuga/resourceAdapter/resourceAdapter.py#L131) and [here](https://github.com/UnivaCorporation/tortuga/blob/master/src/installer/src/tortuga/resourceAdapter/resourceAdapter.py#L442)).
I've tested this in AWS and all of the requested tags are applied as …

Adding requested tags to spot instances

---

kit.json
src/tortuga/resourceAdapter/aws/aws.py

This PR changes how spot instances are handled when a custom hostname is used (i.e., `use_instance_hostname == False`).  The new workflow is:
1. Create a node entry and tag entries
2. Generate an `insertnode_request` for the userdata provided to the spot instance, which means this instance type now will self-register with Tortuga.  The data includes the name of the node so that Tortuga can look up the existing node entry when the instance boots up and registers itself.
3. When the spot instance registers, look up the existing node entry and add some information to it from the AWS instance metadata.  Also look up the existing tag entries and apply them to the instance.
This requires a corresponding update in tortuga core: https://github.com/UnivaCorporation/tortuga/pull/599
In a live AWS …

Spot instance tags fixes

---

kit.json
src/tortuga/resourceAdapter/aws/aws.py
tortuga_kits/awsadapter/events/listeners/scalesets.py
tortuga_kits/awsadapter/files/bootstrap.debian.tmpl
tortuga_kits/awsadapter/files/bootstrap.tmpl

* Standardize method for generating a startup/bootstrap script to be in line with GCE adapter kit (named `generate_startup_script`; has same arguments)
* Add a method for creating an AWS launch template from a combination of hardware profile, software profile, and resource adapter profile
* Make method for getting a boto3 connection generic for EC2 and autoscaling APIs
* Rework scale sets
* Use launch templates rather than launch configurations
* Can provide an existing launch template rather than creating one for each auto-scaling group
* Use `boto3` (`boto` does not seem to allow you to create auto-scaling groups from launch templates)
* Update scale set listener to get launch template name from scale set resource request and do some validation so that user must provide either a launch …

Rework scale sets

---

requirements.txt

Also include an update to contemporary releases that drop support for Python 2.6 and 3.3 (`awscli==1.16.x` appears to be dead as of January 2020). Here are the dependencies of the relevant packages as of March 2020:
```
╰─>$ grep "Requires.*boto" awscli-1.18.28.dist-info/METADATA boto-2.49.0.dist-info/METADATA boto3-1.12.28.dist-info/METADATA                                (base)
awscli-1.18.28.dist-info/METADATA:Requires-Dist: botocore (==1.15.28)
boto3-1.12.28.dist-info/METADATA:Requires-Dist: botocore (<1.16.0,>=1.15.28)
```
If you mentally subtract `0.2` from the version numbers above, these dependencies will help you understand why the following is happening:
```
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in …
```

Modify pip requirements to flexibly align adapter with awscli and boto3

---

src/tortuga/resourceAdapter/aws/aws.py
tortuga_kits/awsadapter/events/listeners/scalesets.py

Fixes the issue where attempting to delete a scale set that doesn't exist prevents the corresponding resource request from being deleted. We now catch the exception and check whether it corresponds to an "AutoScalingGroup does not exist" error; and if so, continue on.

Resolve issues with scale set deletion workflow

---

src/tortuga/resourceAdapter/aws/aws.py
tortuga_kits/awsadapter/files/bootstrap.tmpl

When the resource adapter detects that the hostname assigned
to a node doesn't match the hostname as known by AWS record the
custom hostname in the 'tortuga-name' tag.  This will allow
consumers of the AWS API to determine the instances hostname.

Record custom hostname in tag

---

src/tortuga/resourceAdapter/aws/aws.py
tortuga_kits/awsadapter/files/cloud-config-compute-redhat.yaml

1. cloud-init recipes do not presently have the ability to render the
insertnode_request variable which identifies the URI at which the
node must self-register upon boot. This is critical for instances
which are created "by AWS" rather than "by Launch" as in Spot and
Auto Scaling Groups.
2. In example cloud-init config file, demonstrate how SystemD can be
used to ensure that node self-registration is repeated until success.
This allows the Launch/Tortuga service to be down for short durations
while reducing the likelihood of orphaned Spot/ASG instances.

Enabling templating of insertnode_request

---

tortuga_kits/awsadapter/files/cloud-config-compute-redhat.yaml

Puppet cannot be successful for spot or scale set instances unless those nodes have registered with Tortuga already. These changes ensure that ordering and also ensure that all the relevant services retry until they succeed and then never run again (e.g. Puppet runs only once).

Ensure ordering of spot/scale set node registration before Puppet

---

src/tortuga/resourceAdapter/aws/aws.py
src/tortuga/resourceAdapter/aws/settings.py
tortuga_kits/awsadapter/components/management/component.py
tortuga_kits/awsadapter/components/management/tasks.py

These changes allow for the registration of a periodic task
that will go through the spot requests that have yet to have
a successfull tortuga node reach the installed state.  The task
will delete instances and tracked requests that never obtain
an instance that gets to the installed state.

Add celery based watchdog for spot instances

---

tortuga_kits/awsadapter/files/cloud-config-compute-redhat.yaml

Without `--fail` the cURL command will exit with code 0 even when non-20X HTTP status is returned. This ensures that HTTP failures are captured as non-0 exit codes and triggers the retry `on-failure` mechanism of SystemD.

Add --fail to curl call on spot registration to ensure retries

---

tortuga_kits/awsadapter/files/bootstrap.tmpl

If the NetworkManager is enabled and we are overriding the dns
name the system now reconfigures network manager and restarts it
to prevent clobbering the custom resolv.conf.

Disable NetworkManager DNS management if we can

---

src/tortuga/resourceAdapter/aws/aws.py

I prefer the approach of including the timezone in the string (because it's unambiguous) to using `datetime.utcnow`. Both functions ultimately rely on the system-configured timezone.
Resolves #231

Support Spot instance requests on systems not configured for UTC

---

src/tortuga/resourceAdapter/aws/aws.py

Make sure AMI exists before attempting to get its block device mappings. Do this for both boto and boto3 connections.
Backport of 76e81e573672e5d5b8644e1eaa2b027df960d8fd.

Backport AMI validity check to 7.1 branch

---

tortuga_kits/awsadapter/files/bootstrap-aws-ubuntu18.py

to destroy sym link to stub file /run/systemd/resolve/stub-resolv.conf and disable
systemd-resolved to manage /etc/resolv.conf avoiding overwriting Tortuga managed dns.

Remove resolv.config file

---

tortuga_kits/awsadapter/files/bootstrap-aws-centos7.py
tortuga_kits/awsadapter/files/bootstrap-aws-centos8.py
tortuga_kits/awsadapter/files/bootstrap-aws-ubuntu18.py
tortuga_kits/awsadapter/files/bootstrap.tmpl

This PR does the following:
- Adds splay to the puppet run
- Tries the puppet run indefinitely
- Shortens a few names to ensure we are still below the byte limit for cloud-init

Add puppet splay, and try-forever loop
